wandb_version: 1

policy_type:
  desc: null
  value: CustomPolicy.CustomPolicy
total_timesteps:
  desc: null
  value: 20000000
learning_rate:
  desc: null
  value: 0.0003
env_name:
  desc: null
  value: CartPole-v1
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683782369.045169
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.11.3
      5: 0.15.2
      8:
      - 5
